<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="StudentCRUDWebForm.aspx.cs" Inherits="CRUD_Operation_GRID.StudentCRUDWebForm" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
    
        <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateEditButton="True" BackColor="White" BorderColor="#336666" BorderStyle="Double" BorderWidth="3px" CellPadding="4" DataKeyNames="Id" DataSourceID="SqlDataSource1" GridLines="Horizontal" ShowFooter="True" AutoGenerateDeleteButton="True">
            <Columns>
                <asp:TemplateField HeaderText="Id" InsertVisible="False" SortExpression="Id">
                    <EditItemTemplate>
                        <asp:Label ID="Label1" runat="server" Text='<%# Eval("Id") %>'></asp:Label>                     
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label1" runat="server" Text='<%# Bind("Id") %>'></asp:Label>
                    </ItemTemplate>
                    <FooterTemplate>
                        <asp:LinkButton onClick="LinkButton1_Click" ValidationGroup="Insert" ID="LinkButton1" runat="server">Insert</asp:LinkButton>
                    </FooterTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Name" SortExpression="Name">
                    <EditItemTemplate>
                        <asp:TextBox ID="NameTextBox1" runat="server" Text='<%# Bind("Name") %>'></asp:TextBox>
                         <asp:RequiredFieldValidator Text="*" ForeColor="Red" ID="RequiredFieldValidator1" runat="server" ErrorMessage="Name Field is Required." Display="Dynamic" ControlToValidate="NameTextBox1" SetFocusOnError="True"></asp:RequiredFieldValidator>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label2" runat="server" Text='<%# Bind("Name") %>'></asp:Label>
                    </ItemTemplate>
                    <FooterTemplate>
                        <asp:TextBox ID="FooterNameTextBox" runat="server"></asp:TextBox>
                        <asp:RequiredFieldValidator ValidationGroup="Insert" Text="*" ForeColor="Red" ID="RequiredFieldValidator2" runat="server" ErrorMessage="Please Insert in Name Field." Display="Dynamic" ControlToValidate="FooterNameTextBox" SetFocusOnError="True"></asp:RequiredFieldValidator>

                    </FooterTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Gender" SortExpression="Gender">
                    <EditItemTemplate>
                         <asp:DropDownList ID="DropDownList1" runat="server" Text='<%# Bind("Gender") %>'>
                            <asp:ListItem>Select</asp:ListItem>
                            <asp:ListItem>Male</asp:ListItem>
                            <asp:ListItem>Female</asp:ListItem>
                        </asp:DropDownList>
                        <asp:RequiredFieldValidator Text="*" ForeColor="Red" InitialValue="Select" ID="RequiredFieldValidator3" runat="server" ErrorMessage="Select Gender." Display="Dynamic" ControlToValidate="DropDownList1" SetFocusOnError="True"></asp:RequiredFieldValidator>
                        
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label3" runat="server" Text='<%# Bind("Gender") %>'></asp:Label>
                    </ItemTemplate>
                    <FooterTemplate>
                        <asp:DropDownList ID="FooterDDLGender" runat="server">
                            <asp:ListItem>Select</asp:ListItem>
                            <asp:ListItem>Male</asp:ListItem>
                            <asp:ListItem>Female</asp:ListItem>
                        </asp:DropDownList>
                        <asp:RequiredFieldValidator ValidationGroup="Insert" Text="*" ForeColor="Red" InitialValue="Select" ID="RequiredFieldValidator4" runat="server" ErrorMessage="Select Gender." Display="Dynamic" ControlToValidate="FooterDDLGender" SetFocusOnError="True"></asp:RequiredFieldValidator>
                    </FooterTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Class" SortExpression="Class">
                    <EditItemTemplate>
                        <asp:TextBox ID="ClassTextBox" runat="server" Text='<%# Bind("Class") %>'></asp:TextBox>
                         <asp:RequiredFieldValidator Text="*" ForeColor="Red"  ID="RequiredFieldValidator5" runat="server" ErrorMessage="Please Insert Class." Display="Dynamic" ControlToValidate="ClassTextBox" SetFocusOnError="True"></asp:RequiredFieldValidator>
                        <asp:RegularExpressionValidator ID="RegularExpressionValidator1" runat="server" ErrorMessage="Invalid String Number Only on Class" Display="Dynamic" Text="*" ControlToValidate="ClassTextBox" SetFocusOnError="True" ValidationExpression="^\d+" ForeColor="Red"></asp:RegularExpressionValidator>
                     </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label4" runat="server" Text='<%# Bind("Class") %>'></asp:Label>
                    </ItemTemplate>
                    <FooterTemplate>
                        <asp:TextBox ID="FooterClass" runat="server"></asp:TextBox>
                      <asp:RequiredFieldValidator ValidationGroup="Insert" Text="*" ForeColor="Red"  ID="RequiredFieldValidator6" runat="server" ErrorMessage="Please Insert Class." Display="Dynamic" ControlToValidate="FooterClass" SetFocusOnError="True"></asp:RequiredFieldValidator>
                       <asp:RegularExpressionValidator ValidationGroup="Insert" ID="RegularExpressionValidator2" runat="server" ErrorMessage="Invalid String Number Only on Class" Display="Dynamic" Text="*" ControlToValidate="FooterClass" SetFocusOnError="True" ValidationExpression="^\d+" ForeColor="Red"></asp:RegularExpressionValidator>
                    </FooterTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Sec" SortExpression="Sec">
                    <EditItemTemplate>
                        <asp:TextBox ID="SecTextBox" runat="server" Text='<%# Bind("Sec") %>'></asp:TextBox>
                      <asp:RequiredFieldValidator Text="*" ForeColor="Red"  ID="RequiredFieldValidator6" runat="server" ErrorMessage="Please Insert Sec." Display="Dynamic" ControlToValidate="SecTextBox" SetFocusOnError="True"></asp:RequiredFieldValidator>

                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label5" runat="server" Text='<%# Bind("Sec") %>'></asp:Label>
                    </ItemTemplate>
                    <FooterTemplate>
                        <asp:TextBox ID="FooterSec" runat="server"></asp:TextBox>
                       <asp:RequiredFieldValidator ValidationGroup="Insert" Text="*" ForeColor="Red"  ID="RequiredFieldValidator7" runat="server" ErrorMessage="Please Insert Sec." Display="Dynamic" ControlToValidate="FooterSec" SetFocusOnError="True"></asp:RequiredFieldValidator>
                       
                    </FooterTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Phone" SortExpression="Phone">
                    <EditItemTemplate>
                        <asp:TextBox ID="PhoneTextBox" runat="server" Text='<%# Bind("Phone") %>'></asp:TextBox>
                        <asp:RequiredFieldValidator Text="*" ForeColor="Red"  ID="RequiredFieldValidator8" runat="server" ErrorMessage="Please Insert Phone Number." Display="Dynamic" ControlToValidate="PhoneTextBox" SetFocusOnError="True"></asp:RequiredFieldValidator>
                       <asp:RegularExpressionValidator ID="RegularExpressionValidator3" runat="server" ErrorMessage="Invalid String Number Only on Phone" Display="Dynamic" Text="*" ControlToValidate="PhoneTextBox" SetFocusOnError="True" ValidationExpression="^\d+" ForeColor="Red"></asp:RegularExpressionValidator>
                  
                         </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label6" runat="server" Text='<%# Bind("Phone") %>'></asp:Label>
                    </ItemTemplate>
                    <FooterTemplate>
                        <asp:TextBox ID="FooterPhone" runat="server"></asp:TextBox>
                        <asp:RequiredFieldValidator ValidationGroup="Insert" Text="*" ForeColor="Red"  ID="RequiredFieldValidator9" runat="server" ErrorMessage="Please Insert Phone Number." Display="Dynamic" ControlToValidate="FooterPhone" SetFocusOnError="True"></asp:RequiredFieldValidator>
                       <asp:RegularExpressionValidator ValidationGroup="Insert" ID="RegularExpressionValidator4" runat="server" ErrorMessage="Invalid String Number Only on Phone" Display="Dynamic" Text="*" ControlToValidate="FooterPhone" SetFocusOnError="True" ValidationExpression="^\d+" ForeColor="Red"></asp:RegularExpressionValidator>

                    </FooterTemplate>
                </asp:TemplateField>
            </Columns>
            <FooterStyle BackColor="White" ForeColor="#333333" />
            <HeaderStyle BackColor="#336666" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#336666" ForeColor="White" HorizontalAlign="Center" />
            <RowStyle BackColor="White" ForeColor="#333333" />
            <SelectedRowStyle BackColor="#339966" Font-Bold="True" ForeColor="White" />
            <SortedAscendingCellStyle BackColor="#F7F7F7" />
            <SortedAscendingHeaderStyle BackColor="#487575" />
            <SortedDescendingCellStyle BackColor="#E5E5E5" />
            <SortedDescendingHeaderStyle BackColor="#275353" />
        </asp:GridView>
        <asp:ValidationSummary ValidationGroup="Insert" ID="ValidationSummary1" runat="server" BackColor="#999999" ForeColor="Red" />
         <asp:ValidationSummary  ID="ValidationSummary2" runat="server" BackColor="#999999" ForeColor="Red" />
    </div>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" DeleteCommand="DELETE FROM [StudentTable] WHERE [Id] = @Id" InsertCommand="INSERT INTO [StudentTable] ([Name], [Gender], [Class],[Sec],[Phone]) VALUES (@Name, @Gender, @Class, @Sec, @Phone)" SelectCommand="SELECT * FROM [StudentTable]" UpdateCommand="UPDATE [StudentTable] SET [Name] = @Name, [Gender] = @Gender, [Class] = @Class, [Sec] = @Sec, [Phone] = @Phone WHERE [Id] = @Id">
            <DeleteParameters>
                <asp:Parameter Name="Id" Type="Int32" />
            </DeleteParameters>
            <InsertParameters>
                <asp:Parameter Name="Name" Type="String" />
                <asp:Parameter Name="Gender" Type="String" />
                <asp:Parameter Name="Class" Type="Int32" />
                <asp:Parameter Name="Sec"  Type="String" />
                <asp:Parameter Name="Phone"  Type="String" />
            </InsertParameters>
            <UpdateParameters>
                <asp:Parameter Name="Name" Type="String" />
                <asp:Parameter Name="Gender" Type="String" />
                <asp:Parameter Name="Class" Type="Int32" />
                <asp:Parameter Name="Sec"  Type="String" />
                <asp:Parameter Name="Phone"  Type="String" />
                <asp:Parameter Name="Id" Type="Int32" />
            </UpdateParameters>
        </asp:SqlDataSource>
    </form>
</body>
</html>
